### ISSUE TITLE
Bug open ScanReport in RabbitInAHat v0.10.8

### ISSUE THREAD

**Issue by elisahenke** [OHDSI/WhiteRabbit#376] opened 2023-04-21 06:22 UTC
Cannot import ScanReport.xlsx in RabbitInAHat v0.10.8.

Steps to reproduce the behavior for RabbitInAHat:
1. Open scan report
2. Select file (ScanReport.xlsx)
3. Error: Invalid File Format

**Comment by janblom** [comment] 2023-04-21 10:02
Hi @elisahenke ,

I am unable to reproduce this, at least with the small set of csv's that I use for testing (attached).
Steps taken:
1. Perform source scan on csv files with whiterabbit
2. Open the generated xlsx file with rabbitinahat => no error, expected source tables are visible

Could you try starting rabbitinahat from the command line, repeat the steps that result in the error and share the stack trace that should be visible in your command window?

Thanks in advance,
Jan

[ScanReport.xlsx](https://github.com/OHDSI/WhiteRabbit/files/11294596/ScanReport.xlsx)
[person.csv](https://github.com/OHDSI/WhiteRabbit/files/11294597/person.csv)
[cost.csv](https://github.com/OHDSI/WhiteRabbit/files/11294599/cost.csv)

**Comment by elisahenke** [comment] 2023-04-21 11:30
Hi @janblom, sorry for the confusion. Now it also worked for my ScanReport. Thanks for helping!

Best,
Elisa

**Comment by janblom** [comment] 2023-04-21 11:34
Hi @elisahenke , well that is good news, thanks for letting me know.
Closing this issue.

**Closed by janblom** 2023-04-21 11:34 UTC
Labels: bug
