### ISSUE TITLE
Unable to connect to postgres on Mac OS X

### ISSUE THREAD

**Issue by fredkingham** [OHDSI/WhiteRabbit#343] opened 2022-07-27 19:28 UTC
**Describe the bug**
Unable to connect to a postgres (11.16) on a with java 1.8 using white rabbit v0.10.7

Whether running scan tables or test connection the error is the same
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class net.ucanaccess.jdbc.UcanaccessDriver
```

**To Reproduce**
1. Install home brew as described https://brew.sh/
Then in a terminal
2. ```brew install postgresql@11```
3. ```psql -c "CREATE DATABASE test```
4. Install white rabbit as described by the README https://github.com/OHDSI/WhiteRabbit#getting-started
5. Fill in the settings as shown on the screenshot
6. Press test connection 

**Expected behavior**
A successful connection to the database

**Screenshots**
<img width="1195" alt="Screenshot 2022-07-27 at 20 16 51" src="https://user-images.githubusercontent.com/2175455/181354926-112161bf-02e3-41ad-9bbe-1cd51d292369.png">

**Desktop (please complete the following information):**
Mac (OS X 12.0.1)

**Comment by KeithWTomlin** [comment] 2022-08-10 15:02
I receive exactly the same error message when attempting to test connection of White Rabbit to a postgreSQL database using MacOS 
MacOS version: 12.5
Chip: Apple M1 Pro 
Java version: Java 8 update 341
PostgreSQL version: 14.4
White Rabbit version: v0.10-2.7

**Comment by janblom** [comment] 2022-08-15 15:04
Hi @fredkingham , @KeithWTomlin ,

I have looked into this, and unfortunately I cannot offer a quick solution. There are two things that stand out with this issue:

1. WhiteRabbit does not load the UcanaccesDriiver class by default. This driver is used for Microsoft Access (MSAccess) databases only. It is very likely that this is somehow locally configured to be loaded on your systems, although it is unclear to me how and why;
2. the reported class ("net.ucanaccess.jdbc.UcanaccessDriver") is incorrect for the version of the library that is released with WhiteRabbit. It should be "net.sf.ucanaccess.jdbc.UcanaccessDriver".

While I cannot offer a solution right now, maybe this information can help you to solve the problem, or obtain more information about the cause.

**Comment by joaofonseca9** [comment] 2022-09-28 09:13
Is there any solution yet to connect White Rabbit with Postgres with a Macbook M1 machine?

**Comment by janblom** [comment] 2022-11-01 16:47
I have added a release marked **v0.10.7a** that logs a line to the console window when the system property 'jdbc.drivers' was set before trying to connect to the database (see the screen shot below for an example). Could you test the issue with this version and report any lines from the console window that look like the one in the example?

![image](https://user-images.githubusercontent.com/7388458/199289133-2277550c-acc9-42f3-b2a7-10ece31f865b.png)

**Comment by janblom** [comment] 2023-01-25 14:43
@fredkingham @KeithWTomlin  have you been able to test with v0.10.7a, or otherwise been successful with resolving this issue?

**Comment by janblom** [comment] 2023-02-25 09:05
While working on another issue I could finally reproduce this problem (on Linux/Ubuntu, using java 1.8). While I have not been able to determine exactly why an attempt is made to load the ucanaccess driver, resulting in the error mentioned, I could test and confirm 2 possible workarounds:

1. Use a newer version of Java (I tested with version 11 and 17, and could not reproduce the problem with these versions)
2. Remove repo/ucanaccess-5.0.1.jar (in this case it also works with Java 1.8)

**Closed by janblom** 2023-02-25 09:05 UTC
Labels: bug, WhiteRabbit
