### ISSUE TITLE
WhiteRabbit v.0.10.8a can't generate a scan report (on M1 Mac using latest Java or Azure VM Windows 10 using Java 1.8) 

### ISSUE THREAD

**Issue by heschmidt04** [OHDSI/WhiteRabbit#392] opened 2023-11-20 15:55 UTC
**Describe the bug**
Context - We are limited to external authentication to generate a scan report from a direct connection to Snowflake Cloud or SQL Server through Citrix - both use Okta.
In test of release candidate for Snowflake - external browser Okta authentication for Snowflake connects successfully in Azure VM running Windows 10 and on Mac M1 laptop. 

Consistently the WhiteRabbit tool throws an error generating a scan report. 

In local test with v.10.8. I can't get my local laptop to generate a scan report on a local (127.0.0.1) Postgres database. 
I have tried both version v.10.8 (local) and Release Candidate for Snowflake (RC from Jan at TheHyve) 

**To Reproduce on M1 **
Steps to reproduce the behavior on M1 latop with v.10.8.a:
1. Download https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.10.8
2. Unzip the folder 
3. Set up ini file 
4. run ./whiteRabbit -ini  M1-Snowflake-WhiteRabbit.ini

**To Reproduce on M1 **
Steps to reproduce the behavior on M1 latop with v.10.8.a:
1. Download https://github.com/thehyve/OHDSI-WhiteRabbit/releases/tag/v0.9.3-TheHyve
2. Unzip the folder 
3. Set up ini file 
4. run ./whiteRabbit -ini  WhiteRabbitSnowflake.ini 

**Expected behavior**
The WhiteRabbit app would scan the table(s)
then return a scan report in the folder defined in the .ini file 

**Screenshots**

**M1 Desktop (please complete the following information):**
 - OS: Sonoma 14.1.1
 - Browser Chrome 
 - Version Version 119.0.6045.123 (Official Build) (arm64)
 - Java Version  "17.0.8" 2023-07-18 LTS
 - Snowflake Jarfile 3.9.2 and no JNA jar files needed 

**Azure VM  (please complete the following information):**
 - Device: Azure Windows virtual machine 
 - OS: Windows 10
 - Browser Chrome 
 - Version Version 119.0.6045.159 (32 bit)
 - Java Version 1.8.0_381 
 - Snowflake Jarfile 3.9.2 and JNA jar files in the same CLASSPATH for Windows 10

**Additional context**
** Azure using Snowflake connector with ini file - Attached the screen shots from the Azure Workstation using the Release candidate (Jan from TheHyve). I tested a scan of OMOP PERSON expecting 710 records 
** M1 using local Postgres with ini file - Tested it against an empty database other than Athena vocabulary tables loaded, and told it to scan 10k records of all tables
 - Ini file contents                                    
WORKING_FOLDER = /Users/heidischmidt/Downloads/OHDSI-WhiteRabbit/data/
DATA_TYPE = PostgreSQL
SERVER_LOCATION = 127.0.0.1/chorus_mgb_cdm
USER_NAME = chorus_mgb_cdm
PASSWORD = redacted
DATABASE_NAME = public
DELIMITER = ,                                 # The delimiter that separates values
TABLES_TO_SCAN = *                            # Comma-delimited list of table names to scan. Use "*" (asterix) to include all tables in the database
SCAN_FIELD_VALUES = yes                       # Include the frequency of field values in the scan report? "yes" or "no"
MIN_CELL_COUNT = 5                            # Minimum frequency for a field value to be included in the report
MAX_DISTINCT_VALUES = 1000                    # Maximum number of distinct values per field to be reported
ROWS_PER_TABLE = 100                          # Maximum number of rows per table to be scanned for field values
CALCULATE_NUMERIC_STATS = no                  # Include average, standard deviation and quartiles in the scan report? "yes" or "no"
NUMERIC_STATS_SAMPLER_SIZE = 500              # Maximum number of rows used to calculate numeric statistics
 - Error 
Nov 20, 2023, 10:33:24 AM	Generating scan report
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipFile
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.generateReport(SourceDataScan.java:172)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:117)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain.launchCommandLine(WhiteRabbitMain.java:268)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain.<init>(WhiteRabbitMain.java:126)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain.main(WhiteRabbitMain.java:121)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.zip.ZipFile
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more

** M1 using local Postgres with WhiteRabbit GUI using 1 table 
 - Error also occurs using the WhiteRabbit GUI in local Postgres db just scanning concept_relationship 
 Nov 20, 2023, 10:46:57 AM	Scanning table concept_relationship
Stopped after 100000 rows
Nov 20, 2023, 10:47:41 AM	Generating scan report
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipFile
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.generateReport(SourceDataScan.java:172)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:117)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:1054)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.zip.ZipFile
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 3 more

** M1 using Snowflake connector with ini file makes the connection and an external browser pops up to authenticate. The scan has many more errors 
File attached. 
[M1-whiterabbit-rc-ini-at-cli-errors-11202023.txt](https://github.com/OHDSI/WhiteRabbit/files/13416749/M1-whiterabbit-rc-ini-at-cli-errors-11202023.txt)
![WhiteRabbitGenerateScanReportJavaError](https://github.com/OHDSI/WhiteRabbit/assets/3218969/1881caf8-23ce-4e68-9e4a-17992dcfb768)
![AzureWhiteRabbitExternalSnowflakeBrowserAuth2023-11-16 at 11 25 58 AM](https://github.com/OHDSI/WhiteRabbit/assets/3218969/fffa4358-862e-42bc-b62d-709bccbc9cac)

**Comment by heschmidt04** [comment] 2023-11-20 16:12
And in WhiteRabbit GUI using v.10.8 using a CSV file (generated from Snowflake) generate scan report also fails.
<img width="1920" alt="WhiteRabbit-v-10 8-M1-Mac-Sonoma-14 1 1-11202023" src="https://github.com/OHDSI/WhiteRabbit/assets/3218969/0ee26acf-6bcf-4471-a1a9-25d780522a2a">

**Comment by janblom** [comment] 2023-11-20 20:26
Problem #1 (Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipFile) has been identified as a problem with an older version of WhiteRabbit (resolved in version 0.10.8.a), problem #2 (java.lang.NoSuchMethodError ... XmlOption) is an issue that only occurs with a preview version for Snowflake that I made available to the reporter of this issue. I have found the root cause and a new preview version will be made available within a few days).

**Closed by janblom** 2023-11-20 20:26 UTC
Labels: bug
