### ISSUE TITLE
[RIAH] Deleting a Source Table

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#277] opened 2020-10-07 12:16 UTC
Provide a way for the user to delete source tables

**Comment by ericaVoss** [comment] 2021-04-22 11:25
![bitmoji](https://sdk.bitmoji.com/render/panel/fe4a1c10-cce9-4b4a-a43c-6e707afcc5d1-aa551c6c-f46d-47c8-bfde-c654112dced4-v1.png?transparent=1&palette=1&width=246)
*beg*

**Comment by MaximMoinat** [comment] 2021-04-26 10:21
😄 
A short use case might help. Because why wouldn't you just delete the source tables not needed from the WR scan report? Or just drag unwanted source tables to the bottom of the list (and forget about them)?

**Comment by ericaVoss** [comment] 2021-05-10 12:15
We are in the middle of the mapping, and we stitched several WR scans together to make the RIAH file.

Yes, right now we just make a table grave yard at the bottom.

**Comment by MaximMoinat** [comment] 2021-05-10 12:19
And also filtering tables with 'ctrl-f' can help!

(yes I am trying very hard to solves this without giving me a coding task... 😉  Although I have thought about adding a feature to e.g. move tables/fields to the top with a simple short key, which might also help a bit.)

**Comment by MaximMoinat** [comment] 2021-05-10 12:20
But I will put this on the roadmap, not sure when this will be added.

**Comment by MaximMoinat** [comment] 2021-05-10 12:24
Duplicate of #274

**Closed by MaximMoinat** 2021-05-10 12:24 UTC
Labels: Rabbit-In-A-Hat, enhancement
